FROM codeberg.org/eoelab/cenv:ddev

ENV UV_INDEX_URL="https://mirrors.ustc.edu.cn/pypi/simple"

# install uv
RUN curl -LsSf https://astral.sh/uv/install.sh | env UV_UNMANAGED_INSTALL="/usr/local/bin" sh