# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Base:
    runs-on: runner
    container:
      image: codeberg.org/eoelab/cenv:kaniko
      volumes:
        - kaniko-cache:/cache
    strategy:
      matrix:
        tag: [alpine, debian]
    steps:
      - &checkout
        run: |
          wget -O main.zip https://codeberg.org/eoelab/cenv/archive/refs/heads/main.zip
          unzip -o main.zip
          mv cenv/* .
      - &login
        run: |
          mkdir -p /kaniko/.docker
          cat > /kaniko/.docker/config.json <<EOF
          {
            "auths": {
              "codeberg.org": {
                "auth": "$(echo -n '${{ vars.PM_USER }}:${{ secrets.PM_PAT }}' | base64)"
              }
            }
          }
          EOF
      - run: |
          /kaniko/executor \
            --context Base/${{ matrix.tag }} \
            --dockerfile Base/${{ matrix.tag }}/Dockerfile \
            --destination codeberg.org/${{ forgejo.repository }}:${{ matrix.tag }} \
            --cache=true --no-push-cache \
            --cache-dir /cache \
            --cache-copy-layers --cache-run-layers \
            --single-snapshot
  
  Denv:
    runs-on: runner
    container:
      image: codeberg.org/eoelab/cenv:kaniko
      volumes:
        - kaniko-cache:/cache
    needs: Base
    strategy:
      matrix:
        tag: [c, cpp, python, upython, zig]
    steps:
      - *checkout
      - *login
      - run: |
          /kaniko/executor \
            --context Denv/${{ matrix.tag }} \
            --dockerfile Denv/${{ matrix.tag }}/Dockerfile \
            --destination codeberg.org/${{ forgejo.repository }}:${{ matrix.tag }} \
            --cache=true --no-push-cache \
            --cache-dir /cache \
            --cache-copy-layers --cache-run-layers \
            --single-snapshot
  
  Gpu:
    runs-on: runner
    container:
      image: codeberg.org/eoelab/cenv:kaniko
      volumes:
        - kaniko-cache:/cache
    needs: Denv
    strategy:
      matrix:
        tag: [rocm, cuda]
    steps:
      - *checkout
      - *login
      - run: |
          /kaniko/executor \
            --context Gpu/${{ matrix.tag }} \
            --dockerfile Gpu/${{ matrix.tag }}/Dockerfile \
            --destination codeberg.org/${{ forgejo.repository }}:${{ matrix.tag }} \
            --cache=true --no-push-cache \
            --cache-dir /cache \
            --cache-copy-layers --cache-run-layers \
            --single-snapshot

  Renv:
    runs-on: runner
    container:
      image: codeberg.org/eoelab/cenv:kaniko
      volumes:
        - kaniko-cache:/cache
    needs: Base
    strategy:
      matrix:
        tag: [crane, jre_21, novnc, steam, zine]
    steps:
      - *checkout
      - *login
      - run: |
          /kaniko/executor \
            --context Renv/${{ matrix.tag }} \
            --dockerfile Renv/${{ matrix.tag }}/Dockerfile \
            --destination codeberg.org/${{ forgejo.repository }}:${{ matrix.tag }} \
            --cache=true --no-push-cache \
            --cache-dir /cache \
            --cache-copy-layers --cache-run-layers \
            --single-snapshot

  Cleanup:
    runs-on: runner
    container:
      image: codeberg.org/eoelab/cenv:alpine
      volumes:
        - kaniko-cache:/cache
    needs: [Gpu, Renv]
    if: always()
    steps:
      - name: Clean kaniko cache (older than 14 days)
        run: |
          find /cache -type f -mtime +14 -delete
          find /cache -type d -empty -delete