name: CI

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  Accel:
    runs-on: runner
    container:
      image: codeberg.org/eoelab/cenv:kaniko
    strategy:
      matrix:
        tag: [cuda, oneapi, rocm, rocm712]
    steps:
      - &checkout
        run: |
          wget -O main.zip https://codeberg.org/eoelab/cenv/archive/refs/heads/main.zip
          unzip -o main.zip
          mv cenv/* .
      - &login
        run: |
          mkdir -p /kaniko/.docker
          cat > /kaniko/.docker/config.json <<EOF
          {
            "auths": {
              "codeberg.org": {
                "auth": "$(echo -n '${{ vars.PM_USER }}:${{ secrets.PM_PAT }}' | base64)"
              }
            }
          }
          EOF
      - run: |
          /kaniko/executor \
            --context Accel/${{ matrix.tag }} \
            --dockerfile Accel/${{ matrix.tag }}/Dockerfile \
            --destination codeberg.org/${{ forgejo.repository }}:${{ matrix.tag }} \
            --single-snapshot

  Denv_DBase:
    runs-on: runner
    container:
      image: codeberg.org/eoelab/cenv:kaniko
    strategy:
      matrix:
        tag: [adev, ddev]
    steps:
      - &checkout
        run: |
          wget -O main.zip https://codeberg.org/eoelab/cenv/archive/refs/heads/main.zip
          unzip -o main.zip
          mv cenv/* .
      - &login
        run: |
          mkdir -p /kaniko/.docker
          cat > /kaniko/.docker/config.json <<EOF
          {
            "auths": {
              "codeberg.org": {
                "auth": "$(echo -n '${{ vars.PM_USER }}:${{ secrets.PM_PAT }}' | base64)"
              }
            }
          }
          EOF
      - run: |
          /kaniko/executor \
            --context Denv/DBase/${{ matrix.tag }} \
            --dockerfile Denv/DBase/${{ matrix.tag }}/Dockerfile \
            --destination codeberg.org/${{ forgejo.repository }}:${{ matrix.tag }} \
            --single-snapshot

  Denv_DProgram:
    runs-on: runner
    container:
      image: codeberg.org/eoelab/cenv:kaniko
    needs: Denv_DBase
    strategy:
      matrix:
        tag: [c, cpp, julia, upython, uv, zig]
    steps:
      - *checkout
      - *login
      - run: |
          /kaniko/executor \
            --context Denv/DProgram/${{ matrix.tag }} \
            --dockerfile Denv/DProgram/${{ matrix.tag }}/Dockerfile \
            --destination codeberg.org/${{ forgejo.repository }}:${{ matrix.tag }} \
            --single-snapshot

  Denv_Data:
    runs-on: runner
    container:
      image: codeberg.org/eoelab/cenv:kaniko
    needs: Denv_DBase
    strategy:
      matrix:
        tag: [mysql]
    steps:
      - *checkout
      - *login
      - run: |
          /kaniko/executor \
            --context Denv/Data/${{ matrix.tag }} \
            --dockerfile Denv/Data/${{ matrix.tag }}/Dockerfile \
            --destination codeberg.org/${{ forgejo.repository }}:${{ matrix.tag }} \
            --single-snapshot

  Renv_RProgram:
    runs-on: runner
    container:
      image: codeberg.org/eoelab/cenv:kaniko
    strategy:
      matrix:
        tag: [jre_21, python]
    steps:
      - *checkout
      - *login
      - run: |
          /kaniko/executor \
            --context Renv/RProgram/${{ matrix.tag }} \
            --dockerfile Renv/RProgram/${{ matrix.tag }}/Dockerfile \
            --destination codeberg.org/${{ forgejo.repository }}:${{ matrix.tag }} \
            --single-snapshot

  Renv_Service:
    runs-on: runner
    container:
      image: codeberg.org/eoelab/cenv:kaniko
    strategy:
      matrix:
        tag: [mc_be, novnc, steam]
    steps:
      - *checkout
      - *login
      - run: |
          /kaniko/executor \
            --context Renv/Service/${{ matrix.tag }} \
            --dockerfile Renv/Service/${{ matrix.tag }}/Dockerfile \
            --destination codeberg.org/${{ forgejo.repository }}:${{ matrix.tag }} \
            --single-snapshot

  Renv_Tool:
    runs-on: runner
    container:
      image: codeberg.org/eoelab/cenv:kaniko
    strategy:
      matrix:
        tag: [crane, zine]
    steps:
      - *checkout
      - *login
      - run: |
          /kaniko/executor \
            --context Renv/Tool/${{ matrix.tag }} \
            --dockerfile Renv/Tool/${{ matrix.tag }}/Dockerfile \
            --destination codeberg.org/${{ forgejo.repository }}:${{ matrix.tag }} \
            --single-snapshot

  Jupyter:
    runs-on: runner
    container:
      image: codeberg.org/eoelab/cenv:kaniko
    needs: Renv_RProgram
    strategy:
      matrix:
        tag: [python-nb]
    steps:
      - *checkout
      - *login
      - run: |
          /kaniko/executor \
            --context Jupyter/${{ matrix.tag }} \
            --dockerfile Jupyter/${{ matrix.tag }}/Dockerfile \
            --destination codeberg.org/${{ forgejo.repository }}:${{ matrix.tag }} \
            --single-snapshot