name: CI

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  Base:
    runs-on: runner
    container:
      image: codeberg.org/eoelab/cenv:kaniko
    strategy:
      matrix:
        tag: [alpine, debian]
    steps:
      - &checkout
        run: |
          wget -O main.zip https://codeberg.org/eoelab/cenv/archive/refs/heads/main.zip
          unzip -o main.zip
          mv cenv/* .
      - &login
        run: |
          mkdir -p /kaniko/.docker
          cat > /kaniko/.docker/config.json <<EOF
          {
            "auths": {
              "codeberg.org": {
                "auth": "$(echo -n '${{ vars.PM_USER }}:${{ secrets.PM_PAT }}' | base64)"
              }
            }
          }
          EOF
      - run: |
          /kaniko/executor \
            --context Base/${{ matrix.tag }} \
            --dockerfile Base/${{ matrix.tag }}/Dockerfile \
            --destination codeberg.org/${{ forgejo.repository }}:${{ matrix.tag }} \
            --single-snapshot
  
  Denv:
    runs-on: runner
    container:
      image: codeberg.org/eoelab/cenv:kaniko
    needs: Base
    strategy:
      matrix:
        tag: [c, cpp, python, upython, zig]
    steps:
      - *checkout
      - *login
      - run: |
          /kaniko/executor \
            --context Denv/${{ matrix.tag }} \
            --dockerfile Denv/${{ matrix.tag }}/Dockerfile \
            --destination codeberg.org/${{ forgejo.repository }}:${{ matrix.tag }} \
            --single-snapshot
  
  Gpu:
    runs-on: runner
    container:
      image: codeberg.org/eoelab/cenv:kaniko
    needs: Denv
    strategy:
      matrix:
        tag: [rocm, cuda]
    steps:
      - *checkout
      - *login
      - run: |
          /kaniko/executor \
            --context Gpu/${{ matrix.tag }} \
            --dockerfile Gpu/${{ matrix.tag }}/Dockerfile \
            --destination codeberg.org/${{ forgejo.repository }}:${{ matrix.tag }} \
            --single-snapshot

  Renv:
    runs-on: runner
    container:
      image: codeberg.org/eoelab/cenv:kaniko
    needs: Base
    strategy:
      matrix:
        tag: [bipes, crane, jre_21, novnc, steam, upypi, zine]
    steps:
      - *checkout
      - *login
      - run: |
          /kaniko/executor \
            --context Renv/${{ matrix.tag }} \
            --dockerfile Renv/${{ matrix.tag }}/Dockerfile \
            --destination codeberg.org/${{ forgejo.repository }}:${{ matrix.tag }} \
            --single-snapshot