name: Mirror

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  # Controls when the workflow will run
  schedule:
    # SUN 00:00 UTC
    - cron: '0 0 * * 0'

jobs:
  Mirror:
    runs-on: runner
    container:
      image: codeberg.org/eoelab/cenv:crane
    steps:
      - run: crane auth login codeberg.org -u ${{ vars.PM_USER }} -p ${{ secrets.PM_PAT }}
      - run: crane copy docker.io/alpine:edge codeberg.org/${{ forgejo.repository }}:edge
      - run: crane copy docker.io/library/debian:testing-slim codeberg.org/${{ forgejo.repository }}:testing-slim
      - run: crane copy ghcr.io/kaniko-build/dist/chainguard-dev-kaniko/executor:latest-debug codeberg.org/${{ forgejo.repository }}:kaniko