name: Mirror

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  # Controls when the workflow will run
  schedule:
    # SUN 00:00 UTC
    - cron: '0 0 * * 0'

jobs:
  Mirror:
    runs-on: codeberg-tiny
    container:
      image: codeberg.org/eoelab/cenv:crane
    steps:
      - run: crane auth login codeberg.org -u ${{ vars.PM_USER }} -p ${{ secrets.PM_PAT }}
      - run: crane copy docker.io/alpine:edge codeberg.org/${{ forgejo.repository }}:edge
      - run: crane copy docker.io/library/debian:sid-slim codeberg.org/${{ forgejo.repository }}:sid-slim
      - run: crane copy ghcr.io/kaniko-build/dist/chainguard-dev-kaniko/executor:latest-debug codeberg.org/${{ forgejo.repository }}:kaniko

  OS:
    runs-on: codeberg-tiny
    container:
      image: codeberg.org/eoelab/cenv:kaniko
    needs: Mirror
    strategy:
      matrix:
        tag: [alpine, debian]
    steps:
      - &checkout
        run: |
          wget -O main.zip https://codeberg.org/eoelab/cenv/archive/refs/heads/main.zip
          unzip -o main.zip
          mv cenv/* .
      - &login
        run: |
          mkdir -p /kaniko/.docker
          cat > /kaniko/.docker/config.json <<EOF
          {
            "auths": {
              "codeberg.org": {
                "auth": "$(echo -n '${{ vars.PM_USER }}:${{ secrets.PM_PAT }}' | base64)"
              }
            }
          }
          EOF
      - run: |
          /kaniko/executor \
            --context OS/${{ matrix.tag }} \
            --dockerfile OS/${{ matrix.tag }}/Dockerfile \
            --destination codeberg.org/${{ forgejo.repository }}:${{ matrix.tag }} \
            --single-snapshot